name: AWS Terraform

on:
  push:
    branches: [ $default-branch ]
    paths:
      - "modules/**"
      - "platform/**"
      - "projects/**"
  pull_request:
    branches: [ $default-branch ]
    paths:
      - "modules/**"
      - "platform/**"
      - "projects/**"

jobs:
  label_pull_request:
    name: Label Pull Request with Repo(s)
    runs-on: ubuntu-latest
    steps:
      - uses: adamzolyak/monorepo-pr-labeler-action@patching
      
      - name: Label PRs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ aws_region }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1.2.1
      with:
        terraform_version: latest
        terraform_wrapper: true  
